# Generated by Django 5.2.6 on 2026-02-09 18:02

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=students.models.get_notification_type_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=students.models.get_target_audience_choices, default='all', max_length=20),
        ),
    ]
