# Generated by Django 5.2.6 on 2026-02-09 18:02

import teachers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(choices=teachers.models.get_employment_type_choices, max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(choices=teachers.models.get_qualification_choices, max_length=20),
        ),
    ]
