# Generated by Django 5.2.6 on 2026-02-09 18:02

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=accounts.models.get_user_type_choices, max_length=10),
        ),
    ]
